language: ruby
dist: trusty
sudo: false
rvm:
- 2.4.1
cache: bundler
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
